{'name': 'Odoo Zoho Mail fix',
'summary': "Fix Zoho mail server relaying issue in odoo- like mail sender's email must be same as outgoing mail server email.",
'sequence': 1,
'price': '30',
'currency': 'USD',
'description': "Fix Zoho mail server relaying issue in odoo- like mail sender's email must be same as outgoing mail server email.",
'live_test_url': 'https://youtu.be/AVDvgGVZZ2E',
'category': '',
'version': '17.0.0.2',
'author': 'Keypress IT Services',
'website': 'https://www.keypress.co.in',
'depends': ['base'],
'data': [],
'application': True,
'installable': True,
'auto_install': False,
'images': ['static/description/Banner.png'],}