{'name': 'Amit',
'version': '17.0.0.0',
'summary': 'ddssddss',
'sequence': 1,
'price': 50.0,
'currency': 'USD',
'author': 'Keypress IT Services',
'description': 'ddssddssddss',
'website': 'https://www.keypress.co.in',
'depends': ['base', 'sale', 'stock', 'delivery', 'purchase'],
'data': ['security/ir.model.access.csv', 'views/sale_order_view.xml', 'views/purchase_order_view.xml', 'views/stock_picking_view.xml', 'reports/sale_order_extend_report.xml', 'reports/purchase_quotation_extend_report.xml', 'reports/purchase_order_extend_report.xml', 'reports/product_report_action.xml', 'reports/product_template_report_template_spt.xml', 'reports/product_product_report_template_spt.xml', 'reports/stock_picking_extend.xml', 'reports/delivery_slip_report_extend.xml'],
'application': True,
'auto_install': False,
'live_test_url': 'https://www.youtube.com/watch?v=-zwE9DhFCmA',}