{'name': 'Savan HIRAPARA',
'version': '17.0.0.3',
'summary': 'Summary\n',
'sequence': 1,
'price': 200.0,
'currency': 'INR',
'author': 'Keypress IT Services',
'description': 'Description',
'website': 'https://staging.keypress.co.in',
'depends': ['base', 'sale', 'stock', 'delivery', 'purchase'],
'data': ['security/ir.model.access.csv', 'views/sale_order_view.xml', 'views/purchase_order_view.xml', 'views/stock_picking_view.xml', 'reports/sale_order_extend_report.xml', 'reports/purchase_quotation_extend_report.xml', 'reports/purchase_order_extend_report.xml', 'reports/product_report_action.xml', 'reports/product_template_report_template_spt.xml', 'reports/product_product_report_template_spt.xml', 'reports/stock_picking_extend.xml', 'reports/delivery_slip_report_extend.xml'],
'application': True,
'auto_install': False,
'live_test_url': 'https://staging.keypress.co.in/odoo-apps/17.0/product_image_display_spt',
'images': ['static/description/banner.png'],
'maintainer': 'Keypress IT Services',
'installable': True,
'license': 'OPL-1',
'category': 'Extra Tools',}