{'name': 'Odoo Sale Secondary UOM',
'version': '17.0.0.2',
'sequence': 1,
'category': 'Extra Tools',
'author': 'Keypress IT Services',
'website': 'https://staging.keypress.co.in',
'summary': 'Odoo Sale Secondary UOM',
'depends': ['sale_management', 'kits_product_secondary_units'],
'data': ['views/sale_order_view.xml', 'reports/kits_sale_report_inherit.xml'],
'application': True,
'installable': True,
'auto-install': False,
'live_test_url': 'https://staging.keypress.co.in/odoo-apps/17.0/reports-custom-font',
'images': ['static/description/banner.png'],
'price': 40.5131,
'currency': 'INR',
'description': 'Odoo Sale Secondary UOM',
'maintainer': 'Keypress IT Services',
'auto_install': False,
'license': 'OPL-1',}